[base]
folder = ""
static = ""
domain = ""
sessionKey = ""

[jwt]
secret = ""

[mailer]
host = ''
secure = true
port = 465
user = ''
password = ''


[api]
pathname = [
  "get | /,/version | Static.Tool.readPackageInfo",
  "get | /now | Static.Tool.getDateTime",

  # user
  "get | /user/list | Bot.User.GetUserList",
]